#pragma once

#define APP_CONFIG_BOOT_DELAY_SEC 5
#define APP_CONFIG_CAN_DEFAULT_BAUDRATE 1000000
#define APP_CONFIG_CAN_LOCAL_NODE_ID 0
#define UAVCAN_DEFAULT_NODE_ID 21
#define APP_CONFIG_CAN_AUTO_BAUD_ENABLE 0

#define SHARED_APP_DESCRIPTOR_MAJOR_VERSION 1
#define SHARED_APP_DESCRIPTOR_MINOR_VERSION 0

#define PROFILED_BLOCKING
#define PROFILED_COLOR_ALLOCATED
